// Country → ISO-style flag code for flagcdn.com. Mirrors src/app/scores/page.tsx
// COUNTRY_CODES so the predictor uses the same flag CDN as Scores.
export const PREDICTOR_FLAG_CODES: Record<string, string> = {
  England: 'gb-eng',
  Scotland: 'gb-sct',
  France: 'fr',
  Spain: 'es',
  Germany: 'de',
  Brazil: 'br',
  Argentina: 'ar',
  Portugal: 'pt',
  Netherlands: 'nl',
  Belgium: 'be',
  Italy: 'it',
  Morocco: 'ma',
  USA: 'us',
  Mexico: 'mx',
  Japan: 'jp',
  Colombia: 'co',
  Uruguay: 'uy',
  Croatia: 'hr',
  Senegal: 'sn',
  Canada: 'ca',
  Switzerland: 'ch',
  Ecuador: 'ec',
  'South Korea': 'kr',
  Australia: 'au',
  Czechia: 'cz',
  'Saudi Arabia': 'sa',
  Paraguay: 'py',
  Algeria: 'dz',
  'New Zealand': 'nz',
  Panama: 'pa',
  Ghana: 'gh',
  Haiti: 'ht',
  Turkey: 'tr',
  'Türkiye': 'tr',
  Egypt: 'eg',
  'Ivory Coast': 'ci',
  Jordan: 'jo',
  Qatar: 'qa',
  Tunisia: 'tn',
  'South Africa': 'za',
  'Bosnia & Herzegovina': 'ba',
  'Bosnia and Herzegovina': 'ba',
  Sweden: 'se',
  Iraq: 'iq',
  'DR Congo': 'cd',
  'Curaçao': 'cw',
  Curacao: 'cw',
  'Cape Verde': 'cv',
  Uzbekistan: 'uz',
  Norway: 'no',
  Iran: 'ir',
  Austria: 'at',
  Nigeria: 'ng',
  Serbia: 'rs',
  Poland: 'pl',
}

export function flagUrl(country: string): string {
  const code =
    PREDICTOR_FLAG_CODES[country] ??
    country.toLowerCase().replace(/\s+/g, '-')
  return `https://flagcdn.com/w160/${code}.png`
}
